### ISSUE TITLE
关于heatmap的问题

### ISSUE THREAD

**Issue by Swagzzy** [wenjiaXu/APN-ZSL#13]
你好，想请教一下heatmap是如何输出的？我看到你没有调用你写得方法，可否麻烦你回答一下

**Comment by KORIYN** [comment]
请问您跑出来论文中CUB数据集上，H67.2的结果了吗？

**Comment by HanAccount** [comment]
> 请问您跑出来论文中CUB数据集上，H67.2的结果了吗？
精确度跑到了69.66

**Comment by Swagzzy** [comment]
> 请问您跑出来论文中CUB数据集上，H67.2的结果了吗？

是的 调参之后甚至超过了这个结果 69.66

**Comment by KORIYN** [comment]
可以分享一下参数吗？


| |


|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年11月16日 ***@***.***> 写道：

请问您跑出来论文中CUB数据集上，H67.2的结果了吗？

是的 调参之后甚至超过了这个结果 69.66

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KORIYN** [comment]
可以分享一下参数吗？

**Comment by Swagzzy** [comment]
> 可以分享一下参数吗？
可以给我你的邮箱吗 我直接分享你文档

**Comment by KORIYN** [comment]
***@***.***

谢谢谢谢！



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月18日 16:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [wenjiaXu/APN-ZSL] 关于heatmap的问题 (Issue #13) |

可以分享一下参数吗？
可以给我你的邮箱吗 我直接分享你文档

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KORIYN** [comment]
wanggerong1998@163.com 多谢！

**Comment by wenjiaXu** [comment]
> 你好，想请教一下heatmap是如何输出的？我看到你没有调用你写得方法，可否麻烦你回答一下

你好，
APN-ZSL/model/model_proto.py  第154行return了attention，对于每一张图片，会输出312个attribute attention map，大小是7*7。经过bicubic interpolation之后就可以使用。

**Comment by Gary828** [comment]
> > 请问您跑出来论文中CUB数据集上，H67.2的结果了吗？
> 
> 是的 调参之后甚至超过了这个结果 69.66

您好，请问能分享一下参数吗？感谢
如果能够分享的话，这是我的邮箱 cs.gary.galigo@gmail.com
麻烦您了

**Comment by cdb342** [comment]
> > 可以分享一下参数吗？
> > 可以给我你的邮箱吗 我直接分享你文档

你好，请问可以分享一下参数吗，这是我的邮箱 dobbin.chen@gmail.com

**Comment by myname4423** [comment]
> 
你好，虽然已经2023年了，请问可以分享一下参数吗，我按默认参数只有H66.0，非常需要这个，这是我的邮箱ryuko.zyb.scut@outlook.com，非常感谢！！

**Comment by myname4423** [comment]
> > 可以分享一下参数吗？
> > 可以给我你的邮箱吗 我直接分享你文档
你好，虽然已经2023年了，请问可以分享一下参数吗，我按默认参数只有H66.0，非常需要这个，这是我的邮箱ryuko.zyb.scut@outlook.com，非常感谢！！

**Comment by myname4423** [comment]
> > 可以分享一下参数吗？
> > 可以给我你的邮箱吗 我直接分享你文档

你好，虽然已经2023年了，请问可以分享一下参数吗，我按默认参数只有H66.0，非常需要这个，这是我的邮箱ryuko.zyb.scut@outlook.com，非常感谢！！

**Comment by myname4423** [comment]
> 可以分享一下参数吗？

请问你还留有[Swagzzy](https://github.com/Swagzzy)分享的参数吗，可以分享我一份吗，很需要这个，非常感谢您！

**Comment by getupgogogo** [comment]
> ryuko.zyb.scut@outlook.com

不知是否和你交流下
